[project]
name = "fii-labs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nltk>=3.9.1",
    "pip>=24.2",
    "sentencepiece>=0.2.0",
    "spacy>=3.8.2",
    "torch>=2.4.1",
    "transformers>=4.45.2",
]
